### ISSUE TITLE
Wether the Lipschitz constant of Actnorm layer should less than 1

### ISSUE THREAD

**Issue by Archer666** [jhjacobsen/invertible-resnet#12]
Hello, this is a great work! But I have a question:
To ensure the network reversible，Lipschitz constant must less than 1, and you divide the spectrum norm of conv and fc layer. But, in Actnorm layer, the Lipschitz constant are not linited to less than 1.
Wether it should be limited as the conv and fc layer?

**Comment by jhjacobsen** [comment]
The Actnorm layer has a closed form inverse, so it is not necessary to constrain it.
