### ISSUE TITLE
Hi! I have two questions as follows.                                                                                                                       

### ISSUE THREAD

**Issue by DLwbm123** [jhjacobsen/invertible-resnet#2]

**Comment by DLwbm123** [comment]
1. When "svd_clipping" is set to True, the function "_wrapper_spectral_norm" return conv operations themselves thus do nothing with them. So why "if svd_clipping is true, uses svd clipping to enforce lipschitz constraint"?  2. I notice there is no usage of  "lipschitz.py". could you please explain this? Thanks a lot!

**Comment by jhjacobsen** [comment]
Both are deprecated, removed now.
