### ISSUE TITLE
Error of Inverse Result is Large?

### ISSUE THREAD

**Issue by koalazf99** [jhjacobsen/invertible-resnet#3]
I use your command script to run a classification model and meet these 2 issues.

1. When the model hasn’t been trained, I test its inverse function. And the error of a (3x32x32 sized) picture is only about 0.001 when running 20 inverse iterations. 

   Then I try to load the model after 1 epoch, the reconstruction error is suddenly about 5.

   I load the model after 50, 150, 200 epochs, but none of them can match the untrained model’s inverse error. After 200 epochs, for a (3x3x32 sized) picture, the smallest error is about 0.95.

2. When I use inverse iterations on the trained model, the reconstruction error rises when I use more inverse iterations. It’s strange because I think the more inverse iterations I use, the less inverse error I will get.

Is this result normal? This problem puzzles me a lot.

**Comment by jhjacobsen** [comment]
Can you redo this but with 20 instead of 5 power iterations:

https://github.com/jhjacobsen/invertible-resnet/blob/master/CIFAR_main.py#L34

**Comment by jhjacobsen** [comment]
@koalazf99 did increasing nr. of power iterations solve the problem for you?

**Comment by koalazf99** [comment]
> @koalazf99 did increasing nr. of power iterations solve the problem for you?

So sorry that I forgot to give a quick response.

Increasing the nr. of power iterations seems to be not useful in CIFAR dataset.

I later found that it may be the problem of loading the pretrained model and initializing the iResNet. 

Anyway, the problem is solved now and thanks a lot for your help!
