### ISSUE TITLE
There is no argument called svdclipping

### ISSUE THREAD

**Issue by crownk1997** [jhjacobsen/invertible-resnet#5]
I have tried to run your program by using the command script and I met the following issue.
1.  You do not provide the argument svdclipping in your code. (CIFAR_main.py 241 line)

However, you try to build your model based on this argument on several points. After I carefully checked your code, I found that you just pass this argument several times, but it was not actually used in your model.

**Comment by jhjacobsen** [comment]
Fixed, thanks.
