### ISSUE TITLE
Duplicated argument clipping

### ISSUE THREAD

**Issue by Gsunshine** [jhjacobsen/invertible-resnet#6]
There is a duplicate argument clipping in the latest version that leads to a TypeError.
https://github.com/jhjacobsen/invertible-resnet/blob/master/models/conv_iResNet.py#L185
https://github.com/jhjacobsen/invertible-resnet/blob/master/models/conv_iResNet.py#L287
https://github.com/jhjacobsen/invertible-resnet/blob/master/models/conv_iResNet.py#L294

Script could run normally after removing them.

**Comment by jhjacobsen** [comment]
Thanks, fixed.
