### ISSUE TITLE
code for reproducing Fig 2 (toy density experiments)

### ISSUE THREAD

**Issue by puneetkdokania** [jhjacobsen/invertible-resnet#8]
Could you please provide code for running experiments on the toy (2D) datasets. Not sure if it's in the repo.

**Comment by jhjacobsen** [comment]
we don't provide code for that unfortunately.

**Comment by puneetkdokania** [comment]
okay, thanks for your reply. we are trying to reproduce the toy experiments, if we are out of luck, I'll post some questions here. Thanks!
