### ISSUE TITLE
bits_per_dim

### ISSUE THREAD

**Issue by hjzhang1990** [jhjacobsen/invertible-resnet#9]
HI! Thank you very much for your code. I have a question about the function bits_per_dim: Why do you want to add an 8?

def bits_per_dim(logpx, inputs):
    return -logpx / float(np.log(2.) * np.prod(inputs.shape[1:])) + 8.

Sincerely look forward to your reply!

**Comment by Lmy0217** [comment]
Add noise ~ U(0, 1/256), log 256 = 8
